- app/controllers/bookings_controller.rb
- app/views/bookings/create.html.erb
- app/views/bookings/destroy.html.erb
- app/views/bookings/edit.html.erb
- app/views/bookings/index.html.erb
- app/views/bookings/new.html.erb
- app/views/bookings/show.html.erb
- app/views/bookings/update.html.erb
- test/controllers/bookings_controller_test.rb
- created CRUD actions for `BookingController`
> bookings controller all CRUD actions

- app/controllers/tools_controller.rb
- app/views/tools/index.html.erb
- config/routes.rb
- test/controllers/tools_controller_test.rb
Tools controller setup with default routes
> Tools controller default

- app/controllers/bookings_controller.rb
- app/views/bookings/new.html.erb
- config/routes.rb
- test/controllers/bookings_controller_test.rb
- created CRUD actions for BookingsController
> booking CRUD actions

- app/controllers/bookings_controller.rb
- app/views/bookings/edit.html.erb
- app/views/bookings/new.html.erb
- app/views/bookings/show.html.erb
- create `new ` html file, with simple form
- create `edit` html file, with simple form
- create `show` html file
> bookings views files created - new, edit, show

- app/controllers/bookings_controller.rb
- app/views/bookings/edit.html.erb
- app/views/bookings/index.html.erb
- app/views/bookings/new.html.erb
- created form for `edit `booking
- created form for `new `booking
> established HTML forms for new and edit bookings

- Gemfile
- Gemfile.lock
- app/models/user.rb
- db/seeds.rb
Created custom seed file, including test user below:
username: test@test.com
password: 123456
> Created custom seed file

- app/views/bookings/edit.html.erb
- app/views/bookings/new.html.erb
- app/views/bookings/show.html.erb
- show and edit pages for bookings to display seed data
> developed show and edit pages to better display seed date for test

- app/views/bookings/index.html.erb
- app/views/bookings/show.html.erb
- app/views/tools/index.html.erb
- established booking show page for specific tool 
- established tool index page
> booking tool show page and tool index page

- app/controllers/bookings_controller.rb
- config/routes.rb
This list all bookings specific to user
> User Listing Bookings

- db/migrate/20241119143707_add_image_and_username_to_user.rb
- db/migrate/20241119143832_add_image_address_category_to_tools.rb
- db/schema.rb
- added `image` and `username` columns to users
- added `image`, `address` and `category` columns to tools
> added columns to tools and users db

- db/seeds.rb
• added `image` (web scraped), `address` (faker) and `category` (static array) to tool seed
• added `image` (faker) and `username` (faker) to user seed
> updated seed for new columns

- app/views/bookings/index.html.erb
- app/views/tools/index.html.erb
- app/views/tools/show.html.erb
- db/seeds.rb
- added `address`, `image` and `category` to tools show page
- added `address`, `image` and `category` to tools index page
- added `image` to booking show page
> added new columns to tool and booking show and index pages

- app/controllers/tools_controller.rb
- app/models/tool.rb
- app/views/tools/_form.html.erb
- app/views/tools/new.html.erb
- config/routes.rb
This feature implements the functionality to create a tool but dependent on cloudinary iimplementation
> Add tool implementation

- app/assets/stylesheets/application.scss
- corrected missing commas in application scss
> header scss correction

- app/views/shared/_navbar.html.erb
- app/views/tools/index.html.erb
- Conditionally display user image or a default icon based on user session.
- Conditional redirect when unregistered user tries to add a tool
> Fix navigation on index page

- app/controllers/tools_controller.rb
- app/models/tool.rb
- app/views/tools/home.html.erb
- config/routes.rb
- Concluded conditional routing when user isn't authenticated
- Homepage controller action and view
> Create landing page controller action and view

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/views/bookings/edit.html.erb
- app/views/bookings/index.html.erb
- app/views/bookings/new.html.erb
- app/views/bookings/show.html.erb
- app/views/tools/new.html.erb
- app/views/tools/show.html.erb
- added scss for cards and buttons
- updated front end styling for tool show, booking index and booking show
> show page styling

- app/controllers/tools_controller.rb
- app/views/shared/_navbar.html.erb
- app/views/tools/_marker.html.erb
- app/views/tools/home.html.erb
- app/views/tools/listing.html.erb
- config/routes.rb
> general fixes

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_modal-popup.scss
- app/views/bookings/_form.html.erb
- app/views/bookings/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/layouts/application.html.erb
- app/views/tools/_form.html.erb
- app/views/tools/index.html.erb
- app/views/tools/listing.html.erb
- app/views/tools/new.html.erb
- app/views/tools/show.html.erb
- created modals for `new` tool and `new` booking form partials
> turbo modals for form partials

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_address_autocomplete.scss
- app/assets/stylesheets/components/_map.scss
- app/javascript/controllers/address_autocomplete_controller.js
- app/javascript/controllers/map_controller.js
- app/views/tools/_form.html.erb
- app/views/tools/index.html.erb
> map-correction

- app/controllers/tools_controller.rb
- app/views/tools/edit.html.erb
- app/views/tools/show.html.erb
- config/routes.rb
- Action to update details of a tool
- Action to delete a tool and it's assciated bookings
> Updating and Deleting a Tool

- .vscode/settings.json
- app/controllers/tools_controller.rb
- app/views/tools/home.html.erb
- app/views/tools/index.html.erb
This PR implements search functionality for home and index page
> search implementation

- app/views/tools/home.html.erb
- app/views/tools/index.html.erb
- app/views/tools/show.html.erb
- db/migrate/20241121143027_add_image_url_to_tools.rb
- db/schema.rb
- db/seeds.rb
- corrected demo seed data for tools and users
> create demo seed

- app/controllers/bookings_controller.rb
- app/helpers/application_helper.rb
- app/views/bookings/_form.html.erb
- app/views/bookings/index.html.erb
- app/views/bookings/new.html.erb
- app/views/bookings/show.html.erb
- config/routes.rb
Added Bookings show page. Added confirmation message. 
Fixed routing error from Booking completion -> Booking show page. 
Removed redundant routes. 
Added format price helper method.
> Added bookings show page. Routed new bookings page to booking#show page.

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/components/_search-bar.scss
- app/controllers/tools_controller.rb
- app/views/bookings/_marker.html.erb
- app/views/shared/_navbar.html.erb
- app/views/tools/_marker.html.erb
- app/views/tools/home.html.erb
- app/views/tools/index.html.erb
- app/views/tools/show.html.erb
corrected map sizing on tool `index`, `show `and booking `show`
> Map sizing

- app/assets/stylesheets/components/_card.scss
- app/views/tools/index.html.erb
- db/seeds.rb
inputted ellipsis text overflow for tool `index `page description
> text overflow for index pages

- app/helpers/application_helper.rb
- app/views/bookings/index.html.erb
- app/views/bookings/new.html.erb
- app/views/bookings/show.html.erb
- app/views/tools/home.html.erb
- app/views/tools/index.html.erb
- app/views/tools/show.html.erb
Added new price calculator methods to render decimal places, and to display total booking price.
Fixed cancel booking button in booking#new
> Price and button fixes

- app/controllers/bookings_controller.rb
- app/views/bookings/_form.html.erb
Fixed booking show map page. 
Added cancel button to booking form.
> Fix booking show map

- app/assets/stylesheets/application.scss
- app/views/bookings/index.html.erb
- db/seeds.rb
styling on more listings div in booking index page, resized map and cards
> resized more listings div elements
